MACRO(ADD_TARGET_TO_TEST TARGET_NAME TEST_NAME TEST_FILE LINKED_LIBRARIES)
    SET(CURRENT_TARGET ${TARGET_NAME}.${TEST_NAME})

    ADD_EXECUTABLE(
        ${CURRENT_TARGET}
        ${TEST_FILE}
    )

    TARGET_LINK_LIBRARIES(
        ${CURRENT_TARGET}
        ${GTEST_LIBRARIES}
        ${LINKED_LIBRARIES}
        ${CMAKE_THREAD_LIBS_INIT}
    )

    ADD_TEST(NAME ${CURRENT_TARGET} COMMAND ${CURRENT_TARGET})
ENDMACRO()